---
header-includes:
- \usepackage{float}
- \usepackage[utf8]{inputenc}
- \usepackage[spanish, es-tabla]{babel}\decimalpoint
output:
  pdf_document: default
  html_document: default
fontsize: 12pt
papersize: letter
geometry: margin = 1in
language: "es"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
library(knitr)
library(kableExtra)
library(tidyverse)
```


**Estadística II - Taller 08$\hspace{1.6cm}$Semestre: 2023-01**

**Profesores: Francisco Javier Rodríguez Cortés, Julieth Verónica Guarín Escudero**

**Monitor: Matheo Muñoz Betancur**

$\rule{6.5in}{1pt}$

1. Responda las siguientes preguntas.
a) Suponga que se ajusta un modelo de regresión con una variable categórica, sin interacción, ¿dicho modelo genera c rectas secantes?
b) En un modelo de regresión lineal simple ajustado solo con variables cualitativas, las rectas generadas son horizontales.
c) El parámetro $\beta_j$ es la media de $Y$ en la categoría $j$ en el modelo de  regresión $Y = \beta_0 + \sum_{k = 1}^{c-1}\beta_k I_{k}+\varepsilon; \  \varepsilon \stackrel{iid}{\sim}\mathcal{N}(0, \sigma^2)$, en caso de que no, ¿cuál es la media?
d) ¿La interacción entre variable numérica y las indicadoras asociadas a una variable categórica hace variar la tasa de cambio de la respuesta dada por la predictora numérica en cada categoría de la variable categórica?

2. Use la base de datos mtcars para ajustar el siguiente modelo $$mpg = \beta_0 + \beta_1 \text{wt} + \beta_2 \text{I}_1 + \beta_3 \text{I}_2 + \beta_4 \text{wt}\times\text{I}_1 + \beta_5 \text{wt}\times\text{I}_1 + \varepsilon; \  \varepsilon \stackrel{iid}{\sim}\mathcal{N}(0, \sigma^2)$$ 
Intreprete los coeficientes de la regresión.

3. Usando la base de datos rock lleve a cabo los métodos de selección forward, backward y stepwise. Concluya cual de los tres modelos obtenidos es el mejor. Para dicha tarea se puede apoyar en la tabla de todas las regresiones posibles.